# Setup rouster aliases
alias rind="\$AVER_SOURCE/rouster/rind"
alias r=rind

alias r.aliases="\$AVER_SOURCE/rouster/rind aliases"
alias r.bash="\$AVER_SOURCE/rouster/rind bash"
alias r.build="\$AVER_SOURCE/rouster/rind build"
alias r.deploy="\$AVER_SOURCE/rouster/rind deploy"
alias r.env="\$AVER_SOURCE/rouster/rind env"
alias r.envs="\$AVER_SOURCE/rouster/rind envs"
alias r.exec="\$AVER_SOURCE/rouster/rind exec"
alias r.kill="\$AVER_SOURCE/rouster/rind kill"
alias r.logs="\$AVER_SOURCE/rouster/rind logs"
alias r.nuke="\$AVER_SOURCE/rouster/rind nuke"
alias r.rm="\$AVER_SOURCE/rouster/rind rm"
alias r.run="\$AVER_SOURCE/rouster/rind run"
alias r.port="\$AVER_SOURCE/rouster/rind port"
alias r.ps="\$AVER_SOURCE/rouster/rind ps"
alias r.pull="\$AVER_SOURCE/rouster/rind pull"
alias r.stop="\$AVER_SOURCE/rouster/rind stop"
alias r.test_all_envs="\$AVER_SOURCE/rouster/rind test_all_envs"
alias r.test_env="\$AVER_SOURCE/rouster/rind test_env"
alias r.up="\$AVER_SOURCE/rouster/rind up"
