# Setup rouster aliases
alias rouster="/aver/rouster/rouster.py"
alias r="rouster"

alias r.bash="rouster bash"
alias r.build="rouster build"
alias r.deploy="rouster deploy"
alias r.env="rouster env"
alias r.exec="rouster exec"
alias r.kill="rouster kill"
alias r.logs="rouster logs"
alias r.nuke="rouster nuke"
alias r.rm="rouster rm"
alias r.run="rouster run"
alias r.port="rouster port"
alias r.ps="rouster ps"
alias r.pull="rouster pull"
alias r.stop="rouster stop"
alias r.test="rouster test"
alias r.up="rouster up"
